### PR TITLE
Add Austrian ATrustSmartCard SCU

### PR DESCRIPTION
**Pull request by LeilaZarban**
- [ ] You've read the [Contributor Guide](https://github.com/fiskaltrust/.github/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/fiskaltrust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

{Summary of the changes}

## Description

{Detail}

Fixes #{issue number}

### CODE REVIEW

**Comment by LeilaZarban** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by LeilaZarban** [comment]
recheck

**Comment by TSchmiedlechner** [comment]
recheck

**Comment by TSchmiedlechner** [comment]
recheck

**Review by forsthug — APPROVED** [review]

**Review by forsthug — APPROVED** [review]

**Pull request merged**
